### ISSUE TITLE
s/clubhouse/shortcut

### ISSUE THREAD

**Issue by kuritz** [farmersdog/clubhouse-workflow-action#12]
Clubhouse has changed their name to `shortcut` and correspondingly changed the format of ticket IDs from `ch1234` to `sc-1234`. The action needs to be updated to account for this change.

**Comment by fabioknoedt** [comment]
@kuritz I think it is quite a simple PR to change from `ch` to `sc` but it would probably make more sense to deprecate this action and create a new one with the new name `shortcut-workflow-action` and add those changes. Maybe something the author @farmersbot wants to do?

**Comment by Dmitrev** [comment]
I attempted a fix, see #13, will need some testing

**Comment by Dmitrev** [comment]
@kuritz could you take a look at #13 ?
