### ISSUE TITLE
Uppercase is not recognized

### ISSUE THREAD

**Issue by fabioknoedt** [farmersdog/clubhouse-workflow-action#8]
Hi there, great workflow action!

I have noticed that when we use uppercase Clubhouse ticket names, the action doesn't pick those up. For example:

```
### Features

ch1234 Shiny New Thing <---- that's OK
[ch9876] Bug In Disguise <---- that's OK
CH1234 Shiny New Thing <---- that's NOT reconigzed 
[CH9876] Bug In Disguise <---- that's NOT reconigzed
```

**Comment by kuritz** [comment]
Hey @fabioknoedt apologies for the really slow reply here. This should be fixed in today's release.

**Comment by fabioknoedt** [comment]
@kuritz that's great! thanks!
